# Generated by Django 5.2.8 on 2025-12-08 14:52

import django.db.models.deletion
import django.utils.timezone
import one_shop.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('selected_color', models.CharField(blank=True, max_length=50, null=True)),
                ('seledcted_color', models.CharField(blank=True, max_length=50, null=True)),
                ('selected_quantity', models.IntegerField(blank=True, null=True)),
                ('selected_size', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=one_shop.models.get_uuid, editable=False, primary_key=True, serialize=False)),
                ('lastName', models.CharField(max_length=35)),
                ('firstName', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('country', models.CharField(max_length=30)),
                ('countryCode', models.CharField(max_length=30)),
                ('address', models.TextField(blank=True, null=True)),
                ('joined_at', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('reset_token', models.CharField(blank=True, max_length=30, null=True)),
                ('token_expiration', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('ordered_items', models.JSONField()),
                ('shipping_method', models.CharField(max_length=100)),
                ('shipping_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_time', models.CharField(max_length=100)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('ordered_at', models.DateField(auto_now_add=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='one_shop.address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('product_id', models.CharField(max_length=100, unique=True)),
                ('name', models.JSONField()),
                ('description', models.JSONField()),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('skuInfo', models.JSONField()),
                ('specifications', models.JSONField(blank=True, null=True)),
                ('multimediaInfo', models.JSONField(blank=True, null=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('warranty', models.CharField(blank=True, max_length=100, null=True)),
                ('care_instructions', models.TextField(blank=True, null=True)),
                ('release_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('sale_end_date', models.CharField(blank=True, max_length=255, null=True)),
                ('available_shipping', models.JSONField(blank=True, null=True)),
                ('return_policy', models.TextField(blank=True, null=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('social_media_links', models.JSONField(blank=True, null=True)),
                ('orders', models.ManyToManyField(blank=True, related_name='products', to='one_shop.orders')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalCoupon',
            fields=[
                ('id', models.UUIDField(default=one_shop.models.get_uuid, editable=False, primary_key=True, serialize=False)),
                ('global_coupon_code', models.CharField(blank=True, max_length=30, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='global_coupons', to='one_shop.products')),
            ],
        ),
        migrations.CreateModel(
            name='AliExpressRatings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('stars', models.IntegerField()),
                ('review', models.JSONField()),
                ('user', models.JSONField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliratings', to='one_shop.products')),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('stars', models.IntegerField()),
                ('review', models.JSONField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='one_shop.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]