# Generated by Django 5.2.8 on 2025-12-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.TextField(blank=True, null=True)),
                ('header', models.JSONField(default=dict)),
                ('main_category', models.JSONField(default=list)),
                ('category', models.JSONField(default=list)),
                ('banners', models.JSONField(default=list)),
                ('slider', models.JSONField(default=list)),
                ('pop_up', models.JSONField(default=dict)),
                ('count_Down', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]