# Generated by Django 5.2.8 on 2026-01-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_shop', '0002_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='display',
            name='logo',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]