# Generated by Django 5.2.8 on 2026-08-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_shop', '0003_alter_display_id_alter_display_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='isHero',
            field=models.BooleanField(default=False),
        ),
    ]