# Generated by Django 5.2.8 on 2026-08-14 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one_shop', '0005_alter_aliexpressratings_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AliExpressRatings',
            new_name='Rating',
        ),
    ]