# Generated by Django 5.2.8 on 2026-09-07 00:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_shop', '0007_delete_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
