# Generated by Django 5.2.8 on 2026-10-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("one_shop", "0008_alter_rating_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
