# Generated by Django 5.2.8 on 2026-10-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("one_shop", "0009_products_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
