export const categoryList = [
  {
    id: 1,
    label: "Table Lamps",
    value: "table_lamps",
  },
  {
    id: 2,
    label: "Floor Lamps",
    value: "floor_lamps",
  },
  {
    id: 3,
    label: "Wall Lamps",
    value: "wall_lamps",
  },
  {
    id: 4,
    label: "Pendant Lights",
    value: "pendant_lights",
  },
  {
    id: 5,
    label: "Ceiling Lights",
    value: "ceiling_lights",
  },
  {
    id: 6,
    label: "Bedside Lamps",
    value: "bedside_lamps",
  },
  {
    id: 7,
    label: "Desk & Office Lamps",
    value: "desk_office_lamps",
  },
  {
    id: 8,
    label: "Outdoor Lighting",
    value: "outdoor_lighting",
  },
];
  
  export const series = [
    "Naruto",
    "One Piece",
    "Dragon Ball",
    "Attack on Titan",
    "Fullmetal Alchemist",
    "Death Note",
    "My Hero Academia",
    "Sailor Moon",
    "Bleach",
    "Cowboy Bebop",
    "Neon Genesis Evangelion",
    "Jojo's Bizarre Adventure",
    "Hunter x Hunter",
    "Sword Art Online",
    "Fairy Tail",
    "Code Geass",
    "Gintama",
    "Steins;Gate",
    "K-On!",
    "Re:Zero − Starting Life in Another World",
    "Demon Slayer: Kimetsu no Yaiba",
    "The Promised Neverland",
    "Haikyuu!!",
    "Yu Yu Hakusho",
    "Black Clover",
    "Dr. Stone",
    "Jujutsu Kaisen",
    "Attack on Titan: The Final Season",
    "Fruits Basket",
    "Bungo Stray Dogs",
    "My Next Life as a Villainess: All Routes Lead to Doom!",
    "Overlord",
    "A Silent Voice",
    "Your Lie in April",
    "Clannad",
    "Kimi no Na wa.",
    "Spirited Away",
    "Other"
  ];
  export const types = [
    "T-shirts",
    "Shirts",
    "Pants",
    "Dresses",
    "Sweaters",
    "Jackets",
    "Underwear",
    "Swimwear",
    "Activewear",
    "Phones",
    "Tablets",
    "Laptops",
    "Desktops",
    "TVs",
    "Cameras",
    "Audio",
    "Accessories",
    "Furniture",
    "Home Decor",
    "Kitchen & Dining",
    "Bedding",
    "Bath",
    "Storage & Organization",
    "Tools & Home Improvement",
    "Pet Supplies",
    "Posters",
    "Bags",
    "Accessories",
    "Notebooks",
    "Stickers",
    "Figures",
    "Plush Toys",
    "Keychains",
    "Phone Cases",
    "Jewelry",
    "Stationery",
    "Cosplay",
    "Collectibles",
    "Other"
  ];
  
  let productTypes = [{
    name: "Clothing", subcategories: ["T-shirts", "Shirts", "Pants", "Dresses", "Sweaters", "Jackets", "Underwear", "Swimwear", "Activewear",],
  },
  {
    name: "Electronics",
    subcategories: [
      "Phones",
      "Tablets",
      "Laptops",
      "Desktops",
      "TVs",
      "Cameras",
      "Audio",
      "Accessories",
    ],
  },
  {
    name: "Home & Garden",
    subcategories: [
      "Furniture",
      "Home Decor",
      "Kitchen & Dining",
      "Bedding",
      "Bath",
      "Storage & Organization",
      "Tools & Home Improvement",
      "Pet Supplies",
    ],
  },
  {
    name: "Posters",
    subcategories: [
      "Anime",
      "Movies",
      "TV Shows",
      "Music",
      "Art",
      "Photography",
      "Sports",
      "Vintage",
    ],
  },
  {
    name: "Bags",
    subcategories: [
      "Backpacks",
      "Handbags",
      "Totes",
      "Clutches",
      "Luggage & Travel",
      "Messenger Bags",
      "Satchels",
      "Shoulder Bags",
      "Wallets",
    ],
  },
  {
    name: "Accessories",
    subcategories: [
      "Hats",
      "Scarves",
      "Gloves",
      "Sunglasses",
      "Watches",
      "Jewelry",
      "Belts",
      "Hair Accessories",
      "Tech Accessories",
    ],
  },
  {
    name: "Notebooks",
    subcategories: [
      "Blank",
      "Lined",
      "Dotted",
      "Grid",
      "Planners",
      "Journals",
      "Sketchbooks",
      "Notepads",
    ],
  },
  {
    name: "Stickers",
    subcategories: [
      "Vinyl",
      "Paper",
      "Custom",
      "Decals",
      "Emojis",
      "Memes",
      "Pop Culture",
      "Graffiti",
    ],
  },
  {
    name: "Figures",
    subcategories: [
      "Action Figures",
      "Vinyl Figures",
      "Collectible Figures",
      "Model Kits",
      "Statues",
      "Dioramas",
      "Replicas",
      "Bobbleheads",
    ],
  },
  {
    name: "Anime",
    subcategories: [
      "Blu-rays & DVDs",
      "Figures",
      "Plushies",
      "Apparel & Accessories",
      "Posters & Wall Scrolls",
      "Keychains & Lanyards",
      "Artbooks",
      "Manga",
      "Light Novels",
    ],
  },
  ];